#!/usr/bin/env bash
# This Bash script displays information about subdomains.
if [ "$#" -eq 2 ]
then
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
fi