#!/usr/bin/env bash
# script that transfers a file from our client to a server:
# scp [OPTION] [user@]SRC_HOST:]file1 [user@]DEST_HOST:]file2
# 1-The path to the file to be transferred
# 2-The IP of the server we want to transfer the file to
# 3-The username scp connects with
# 4-The path to the SSH private key that scp uses

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    if [ $# -eq 3 ]
    then
        scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
    elif [ $# -eq 4 ]
    then
        scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/ 
    fi
fi
