#!/usr/bin/env bash
# Install nginx on the web-01 server

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx start
echo "Hello World" > /var/www/html/index.nginx-debian.html
