#!/usr/bin/env bash
# Script that reconfigs Nginx server to have a 
# custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World" > /var/www/html/index.nginx-debian.html
file="/etc/nginx/sites-available/default"
config="add_header X-Served-By $HOSTNAME;\n"
sudo sed -i "19i $config" "$file"
sudo service nginx restart