#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt update
sudo apt -y upgrade
sudo apt-get -y install haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
# make a backup of config file
echo "ENABLED=1" >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bk
echo -e "frontend load_balancer\n\tbind *:80\n\toption forwardfor\n\tmode http\n\tdefault_backend web_servers\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend web_servers\n\tbalance roundrobin\n\tserver 3964-web-01 34.148.118.138 check\n\tserver 3964-web-02 34.234.69.169 check\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
