#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, with a sleep of 2, and "I am invincible!!!" when receiving a "SIGTERM" sign
while true
do
    echo "To infinity and beyond"
    trap "echo 'I am invincible!!!'" SIGTERM
    sleep 2
done