#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=1
while [ $i -le 20 ]
do
echo $i
case $i in 
4) echo "bad luck from China";;
9) echo "bad luck from Japan";;
17) echo "bad luck from Italy";;
esac
i=$(( i+1 ))
done