#!/usr/bin/env bash
# Runs nginx as user nginx and listening on port 8080
pkill "apache2"
chmod 755 /etc/nginx/nginx.conf
sed -i '1 i user nginx;' /etc/nginx/nginx.conf
sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
