#!/usr/bin/env bash
#Script reconfigures nginx as to run as nginx user.
pkill "apache2"
chmod 755 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start